build:
  image: node:4.3
  commands:
    - apt-get update; apt-get install -y sudo haproxy; /etc/init.d/haproxy start
    - npm install
    - npm test
    - npm run eslint

compose:
  database:
    image: redis:2.8
