build:
  image: node:8
  commands:
    - apt-get update; apt-get install --ignore-optional -y sudo haproxy; /etc/init.d/haproxy start
    - yarn install --ignore-optional
    - yarn test
    - yarn run eslint

compose:
  database:
    image: redis:2.8
