dist: trusty
sudo: required
language: node_js
node_js:
  - "12"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y haproxy
  - sudo /etc/init.d/haproxy start
install:
  - yarn install --ignore-optional
script:
  - yarn test
  - yarn run eslint
cache:
  yarn: true
services:
  - redis
